"""Compatibility facade for the notebook-derived RAG pipeline.

New code should import from the smaller modules in this package. This file keeps
the existing service layer stable while the notebook core is split gradually.
"""

from __future__ import annotations

from documind_rag.rag.notebook_core import (
    analyze_document,
    analyze_query,
    answer_cross_page,
    build_context,
    build_indexes,
    build_knowledge_base,
    build_token_budget_context,
    build_visual_index,
    classify_and_describe_image,
    compute_answer_confidence,
    compute_confidence,
    decompose_query,
    dense_bm25_scores,
    detect_language,
    discover_visual_regions,
    document_to_chunk,
    embed_image_clip,
    embed_text_clip,
    enrich_visual_candidates,
    extract_claims_with_citations,
    extract_query_filters,
    extract_tables_for_document,
    generate_answer_multimodal,
    generate_answer_text_only,
    get_image_bbox,
    get_surrounding_text,
    hierarchical_summarize,
    llm_judge_score,
    multimodal_retrieve,
    ocr_page_with_boxes,
    pil_to_base64,
    render_chunk_image,
    render_page_image,
    rerank,
    segment_page_regions,
    table_index_scores,
    verify_citations,
)
from documind_rag.rag.notebook_core import ask

__all__ = [
    "analyze_document",
    "analyze_query",
    "answer_cross_page",
    "ask",
    "build_context",
    "build_indexes",
    "build_knowledge_base",
    "build_token_budget_context",
    "build_visual_index",
    "classify_and_describe_image",
    "compute_answer_confidence",
    "compute_confidence",
    "decompose_query",
    "dense_bm25_scores",
    "detect_language",
    "discover_visual_regions",
    "document_to_chunk",
    "embed_image_clip",
    "embed_text_clip",
    "enrich_visual_candidates",
    "extract_claims_with_citations",
    "extract_query_filters",
    "extract_tables_for_document",
    "generate_answer_multimodal",
    "generate_answer_text_only",
    "get_image_bbox",
    "get_surrounding_text",
    "hierarchical_summarize",
    "llm_judge_score",
    "multimodal_retrieve",
    "ocr_page_with_boxes",
    "pil_to_base64",
    "render_chunk_image",
    "render_page_image",
    "rerank",
    "segment_page_regions",
    "table_index_scores",
    "verify_citations",
]
